name: yqp
adopt-info: yqp
summary: yqp is a TUI for exploring the jq command line utility
description: |
  yqp is a terminal user interface (TUI) for exploring the jq command line utility.

  You can use it to run jq queries interactively. If no query is provided, the interface will prompt
  you for one.

  The command accepts an optional query argument which will be executed against the input JSON or
  newline-delimited JSON (NDJSON).
  
  You can provide the input JSON or NDJSON either through a file or via standard input (stdin).

  Usage:
    yqp [query] [flags]

  Flags:
    --config string   path to config file (default is $HOME/.yqp.yaml)
    -f, --file string     path to the input JSON file
    -h, --help            help for yqp
    -t, --theme string    yqp theme
    -v, --version         version for yqp
    
license: MIT
issues: https://github.com/kz6fittycent/yqp
contact: https://github.com/kz6fittycent/yqp
source-code: https://github.com/arch-err/yqp
icon: snap/local/yqp.png

base: core24
grade: stable 
confinement: strict
compression: lzo

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  ppc64el:
    build-on: [ppc64el]
    build-for: [ppc64el]
  s390x:
    build-on: [s390x]
    build-for: [s390x]
    
apps:
  yqp:
    command: bin/yqp
    plugs:
      - home

parts:
  yqp:
    source: https://github.com/arch-err/yqp
    source-type: git
    plugin: go
    build-snaps:
      - go
      
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)" 
