name: 🧪 Test snap can be built on x86_64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]    

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - uses: snapcore/action-build@3bdaa03e1ba6bf59a65f84a751d943d549a54e79 # v1
        id: build

      - uses: diddlesnaps/snapcraft-review-action@40554b42331cf84dab19ef98c382620427f13442 # v1
        with:
          snap: ${{ steps.build.outputs.snap }}
          isClassic: 'false'
          # Plugs and Slots declarations to override default denial (requires store assertion to publish)
          # plugs: ./plug-declaration.json
          # slots: ./slot-declaration.json
